# 시계열 연습문제

In [ ]:
# 라이브러리 기본 참조
# 라이브러리 기본 참조
from hossam import load_data
from pandas import DataFrame
from matplotlib import pyplot as plt
from matplotlib import font_manager as fm
from matplotlib import dates
import seaborn as sb
import numpy as np

# ADF 테스트 - 정상성 확인용
from statsmodels.tsa.stattools import adfuller

# ACF, PACF 테스트
from statsmodels.tsa.stattools import acf, pacf

# ACF, PACF 시각화 기능
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

In [10]:
origin = load_data("temperatures_seoul")
print("\n===== 데이터 크기 확인 =====")
print(f"데이터셋 크기: {origin.shape}")
print(f"열 개수: {origin.shape[1]}")
print(f"행 개수: {origin.shape[0]}")
print("\n===== 타입확인 =====")
print(origin.info())
origin.head()

[data] https://data.hossam.kr/data/lab13_/temperatures_seoul.xlsx
[desc] 1973년 7월 1일부터 2023년 8월 6일까지 서울의 일평균 기온 데이터 (출처: 기상청)
[!] Cannot read metadata

===== 데이터 크기 확인 =====
데이터셋 크기: (18299, 2)
열 개수: 2
행 개수: 18299

===== 타입확인 =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18299 entries, 0 to 18298
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   날짜       18299 non-null  datetime64[ns]
 1   평균기온(℃)  18299 non-null  float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 286.1 KB
None

          날짜  평균기온(℃)
0 1973-07-01     22.7
1 1973-07-02     23.8
2 1973-07-03     27.2
3 1973-07-04     25.2
4 1973-07-05     26.9

In [11]:
df = origin.set_index("날짜")
df

            평균기온(℃)
날짜
1973-07-01     22.7
1973-07-02     23.8
1973-07-03     27.2
1973-07-04     25.2
1973-07-05     26.9
...             ...
2023-08-02     29.7
2023-08-03     29.5
2023-08-04     30.0
2023-08-05     30.3
2023-08-06     29.8

[18299 rows x 1 columns]